import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/41yu2qXhXXL._SX324_BO1,204,203,200_.jpg",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: ["History", "Philosophy"],
    stockQty: 50,
    rating: 4.5,
    pages: 416,
    releaseDate: "2014-02-10",
    aboutAuthor:
      "Yuval Noah Harari is a professor of history and author of several books on historical and philosophical topics.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/714FbKtXS+L.jpg",
    title: "The Power of Now",
    author: "Eckhart Tolle",
    price: 249,
    originalPrice: 399,
    isBestSeller: true,
    category: ["Self-Help"],
    stockQty: 30,
    rating: 4.6,
    pages: 236,
    releaseDate: "1997-09-29",
    aboutAuthor:
      "Eckhart Tolle is a spiritual teacher and author known for his teachings on mindfulness and presence.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81dDwAzxtrL.jpg",
    title: "Becoming",
    author: "Michelle Obama",
    price: 399,
    originalPrice: 599,
    isBestSeller: true,
    category: ["Biography"],
    stockQty: 40,
    rating: 4.8,
    pages: 448,
    releaseDate: "2018-11-13",
    aboutAuthor:
      "Michelle Obama is an American attorney and author. She served as the First Lady of the United States from 2009 to 2017.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71m+kC4vOxL.jpg",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    price: 299,
    originalPrice: 499,
    isBestSeller: false,
    category: ["Psychology", "Finance"],
    stockQty: 20,
    rating: 4.7,
    pages: 512,
    releaseDate: "2011-10-25",
    aboutAuthor:
      "Daniel Kahneman is an Israeli-American psychologist and Nobel laureate. He is known for his work in the field of behavioral economics.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81oMQeXD1PL.jpg",
    title: "Blink: The Power of Thinking Without Thinking",
    author: "Malcolm Gladwell",
    price: 249,
    originalPrice: 399,
    isBestSeller: true,
    category: ["Psychology"],
    stockQty: 10,
    rating: 4.4,
    pages: 320,
    releaseDate: "2005-01-11",
    aboutAuthor:
      "Malcolm Gladwell is a Canadian journalist and author known for his books on social sciences.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81gepf1eMqL.jpg",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 199,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Classics"],
    stockQty: 50,
    rating: 4.8,
    pages: 281,
    releaseDate: "1960-07-11",
    aboutAuthor:
      "Harper Lee was an American novelist widely known for her novel 'To Kill a Mockingbird.'",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg",
    title: "1984",
    author: "George Orwell",
    price: 249,
    originalPrice: 399,
    isBestSeller: true,
    category: ["Dystopian"],
    stockQty: 30,
    rating: 4.6,
    pages: 328,
    releaseDate: "1949-06-08",
    aboutAuthor:
      "George Orwell, whose real name was Eric Arthur Blair, was an English novelist and essayist.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71FTb9X6wsL.jpg",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 299,
    originalPrice: 499,
    isBestSeller: false,
    category: ["Classics"],
    stockQty: 40,
    rating: 4.5,
    pages: 180,
    releaseDate: "1925-04-10",
    aboutAuthor:
      "F. Scott Fitzgerald was an American writer and novelist known for his portrayal of the Jazz Age.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/91HPG31dTwL.jpg",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: 199,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Coming-of-Age", "Drama"],
    stockQty: 0,
    rating: 4.2,
    pages: 277,
    releaseDate: "1951-07-16",
    aboutAuthor:
      "J.D. Salinger was an American writer known for his novel 'The Catcher in the Rye.'",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71jLBXtWJWL.jpg",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    price: 349,
    originalPrice: 599,
    isBestSeller: true,
    category: ["Fantasy"],
    stockQty: 50,
    rating: 4.9,
    pages: 1178,
    releaseDate: "1954-07-29",
    aboutAuthor:
      "J.R.R. Tolkien was an English writer, poet, philologist, and university professor.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/41KjuBg5k8L._SX498_BO1,204,203,200_.jpg",
    title: "Gone Girl",
    author: "Gillian Flynn",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: ["Mystery/Thriller"],
    stockQty: 30,
    rating: 4.4,
    pages: 432,
    releaseDate: "2012-06-05",
    aboutAuthor:
      "Gillian Flynn is an American author known for her psychological thriller novels.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71ErsKpwmrS.jpg",
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    price: 249,
    originalPrice: 399,
    isBestSeller: true,
    category: ["Mystery/Thriller"],
    stockQty: 40,
    rating: 4.2,
    pages: 336,
    releaseDate: "2015-01-13",
    aboutAuthor:
      "Paula Hawkins is a British author known for her thriller novels.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/91Q5dCjc2KL.jpg",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    price: 349,
    originalPrice: 599,
    isBestSeller: false,
    category: ["Mystery/Thriller"],
    stockQty: 20,
    rating: 4.6,
    pages: 592,
    releaseDate: "2003-03-18",
    aboutAuthor:
      "Dan Brown is an American author known for his thriller novels, particularly the Robert Langdon series.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51oVTRsjcqL._SX329_BO1,204,203,200_.jpg",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: ["Mystery/Thriller"],
    stockQty: 10,
    rating: 4.7,
    pages: 336,
    releaseDate: "2019-02-05",
    aboutAuthor:
      "Alex Michaelides is a British-Cypriot author and screenwriter known for his psychological thriller novels.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81UhKOBDrCL.jpg",
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: ["Mystery/Thriller"],
    stockQty: 50,
    rating: 4.5,
    pages: 672,
    releaseDate: "2005-08-23",
    aboutAuthor:
      "Stieg Larsson was a Swedish journalist and author known for his Millennium series of crime novels.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71Q1tPupKjL.jpg",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 199,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Romance"],
    stockQty: 50,
    rating: 4.7,
    pages: 432,
    releaseDate: "1813-01-28",
    aboutAuthor:
      "Jane Austen was an English novelist known for her works of romantic fiction.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/91xD+7HtVfL.jpg",
    title: "Outlander",
    author: "Diana Gabaldon",
    price: 299,
    originalPrice: 449,
    isBestSeller: false,
    category: ["Romance"],
    stockQty: 40,
    rating: 4.5,
    pages: 896,
    releaseDate: "1991-06-01",
    aboutAuthor:
      "Diana Gabaldon is an American author known for the Outlander series of novels.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/710v59ixsEL.jpg",
    title: "The Notebook",
    author: "Nicholas Sparks",
    price: 249,
    originalPrice: 399,
    isBestSeller: true,
    category: ["Romance"],
    stockQty: 40,
    rating: 4.6,
    pages: 272,
    releaseDate: "1996-10-01",
    aboutAuthor:
      "Nicholas Sparks is an American author known for his romance novels, many of which have been adapted into films.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81COeJEEL7L.jpg",
    title: "Me Before You",
    author: "Jojo Moyes",
    price: 279,
    originalPrice: 499,
    isBestSeller: true,
    category: ["Romance"],
    stockQty: 30,
    rating: 4.4,
    pages: 512,
    releaseDate: "2012-01-05",
    aboutAuthor:
      "Jojo Moyes is an English author known for her romantic novels, including Me Before You.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/A1c9bOWb6RL.jpg",
    title: "The Fault in Our Stars",
    author: "John Green",
    price: 199,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Romance"],
    stockQty: 20,
    rating: 4.3,
    pages: 313,
    releaseDate: "2012-01-10",
    aboutAuthor:
      "John Green is an American author known for his young adult novels, including The Fault in Our Stars.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/917TGSXH7RL.jpg",
    title: "Meditations",
    author: "Marcus Aurelius",
    price: 199,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Philosophy"],
    stockQty: 50,
    rating: 4.6,
    pages: 304,
    releaseDate: "180 AD",
    aboutAuthor:
      "Marcus Aurelius was a Roman emperor and philosopher known for his book Meditations.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/9176A9Hpd2L.jpg",
    title: "Thus Spoke Zarathustra",
    author: "Friedrich Nietzsche",
    price: 249,
    originalPrice: 399,
    isBestSeller: false,
    category: ["Philosophy"],
    stockQty: 30,
    rating: 4.4,
    pages: 352,
    releaseDate: "1883",
    aboutAuthor:
      "Friedrich Nietzsche was a German philosopher known for his provocative and influential works.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81Kr+YIWjCL.jpg",
    title: "Beyond Good and Evil",
    author: "Friedrich Nietzsche",
    price: 279,
    originalPrice: 499,
    isBestSeller: true,
    category: ["Philosophy"],
    stockQty: 20,
    rating: 4.5,
    pages: 240,
    releaseDate: "1886",
    aboutAuthor:
      "Friedrich Nietzsche was a German philosopher known for his provocative and influential works.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81PEato5oDL.jpg",
    title: "The Republic",
    author: "Plato",
    price: 299,
    originalPrice: 599,
    isBestSeller: true,
    category: ["Philosophy"],
    stockQty: 10,
    rating: 4.7,
    pages: 416,
    releaseDate: "380 BC",
    aboutAuthor:
      "Plato was an ancient Greek philosopher and the founder of the Academy in Athens.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71qbK90zBjL.jpg",
    title: "The Art of War",
    author: "Sun Tzu",
    price: 199,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Philosophy"],
    stockQty: 50,
    rating: 4.8,
    pages: 273,
    releaseDate: "5th century BC",
    aboutAuthor:
      "Sun Tzu was a Chinese general, military strategist, and philosopher.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/61wADuboi4L.jpg",
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: ["Self-Help"],
    stockQty: 40,
    rating: 4.7,
    pages: 381,
    releaseDate: "1989",
    aboutAuthor:
      "Stephen R. Covey was an American educator, author, and businessman known for his self-help and leadership books.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51-nXsSRfZL._SX328_BO1,204,203,200_.jpg",
    title: "Atomic Habits",
    author: "James Clear",
    price: 249,
    originalPrice: 399,
    isBestSeller: true,
    category: ["Self-Help"],
    stockQty: 30,
    rating: 4.8,
    pages: 320,
    releaseDate: "2018",
    aboutAuthor:
      "James Clear is an author, speaker, and productivity expert known for his work on habits, decision-making, and continuous improvement.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51Hfv2MfNGL._SX331_BO1,204,203,200_.jpg",
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    price: 199,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Self-Help", "Finance"],
    stockQty: 50,
    rating: 4.6,
    pages: 336,
    releaseDate: "1997",
    aboutAuthor:
      "Robert T. Kiyosaki is an entrepreneur and author known for his personal finance and investment advice.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71QKQ9mwV7L.jpg",
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    price: 249,
    originalPrice: 399,
    isBestSeller: true,
    category: ["Self-Help"],
    stockQty: 10,
    rating: 4.4,
    pages: 224,
    releaseDate: "2016",
    aboutAuthor:
      "Mark Manson is a blogger and author known for his self-help and personal development writings.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/919mmNCTaaL.jpg",
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: ["Finance"],
    stockQty: 40,
    rating: 4.6,
    pages: 640,
    releaseDate: "1949",
    aboutAuthor:
      "Benjamin Graham was an American economist and investor known for his value investing philosophy.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71K518cj-jL.jpg",
    title: "A Random Walk Down Wall Street",
    author: "Burton G. Malkiel",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: ["Finance"],
    stockQty: 10,
    rating: 4.6,
    pages: 496,
    releaseDate: "1973",
    aboutAuthor:
      "Burton G. Malkiel is an American economist and writer known for his books on investment strategies and personal finance.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81-QB7nDh4L.jpg",
    title: "The Lean Startup",
    author: "Eric Ries",
    price: 199,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Business"],
    stockQty: 50,
    rating: 4.7,
    pages: 336,
    releaseDate: "2011",
    aboutAuthor:
      "Eric Ries is an entrepreneur and author known for his methodology on lean startup and continuous innovation.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/41kONb0oymL._SX330_BO1,204,203,200_.jpg",
    title: "The E-Myth Revisited",
    author: "Michael E. Gerber",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: ["Business"],
    stockQty: 40,
    rating: 4.6,
    pages: 268,
    releaseDate: "1995",
    aboutAuthor:
      "Michael E. Gerber is an author and small business expert known for his insights on entrepreneurship and the E-Myth concept.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/61YfNhp-6uL.jpg",
    title: "Good to Great",
    author: "Jim Collins",
    price: 249,
    originalPrice: 399,
    isBestSeller: false,
    category: ["Business"],
    stockQty: 20,
    rating: 4.5,
    pages: 400,
    releaseDate: "2001",
    aboutAuthor:
      "Jim Collins is a researcher and author known for his work on company sustainability and high-performance organizations.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51MLvC+JryL.jpg",
    title: "The Four Steps to the Epiphany",
    author: "Steve Blank",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: ["Business"],
    stockQty: 10,
    rating: 4.6,
    pages: 280,
    releaseDate: "2003",
    aboutAuthor:
      "Steve Blank is an entrepreneur and author known for his work on customer development and the lean startup methodology.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/811pr+4v89L.jpg",
    title: "The Innovator's Dilemma",
    author: "Clayton M. Christensen",
    price: 199,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Business"],
    stockQty: 50,
    rating: 4.7,
    pages: 286,
    releaseDate: "1997",
    aboutAuthor:
      "Clayton M. Christensen was an American business theorist and professor known for his work on disruptive innovation.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/810u9MkT3SL.jpg",
    title: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: ["Business"],
    stockQty: 40,
    rating: 4.6,
    pages: 304,
    releaseDate: "2014",
    aboutAuthor:
      "Ben Horowitz is a technology entrepreneur and venture capitalist known for his experiences in building and leading startups.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/91y5XODFZ+L.jpg",
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    price: 199,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Biography"],
    stockQty: 35,
    rating: 4.7,
    pages: 352,
    releaseDate: "June 25, 1947",
    aboutAuthor:
      "Anne Frank was a Jewish girl who documented her experiences during the Holocaust in her diary. Her writings provide a poignant and powerful account of life in hiding and have become an important historical record.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51ZaFL6B7lL.jpg",
    title: "Hamlet",
    author: "William Shakespeare",
    price: 199,
    originalPrice: 299,
    isBestSeller: false,
    category: ["Drama"],
    stockQty: 30,
    rating: 4.6,
    pages: 320,
    releaseDate: "1603",
    aboutAuthor:
      "William Shakespeare was an English poet, playwright, and actor widely regarded as the greatest writer in the English language. His works, including 'Hamlet,' have had a profound and lasting impact on literature and theater.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/91D4YvdC0dL.jpg",
    title: "Brave New World",
    author: "Aldous Huxley",
    price: 249,
    originalPrice: 399,
    isBestSeller: true,
    category: ["Dystopian"],
    stockQty: 20,
    rating: 4.5,
    pages: 288,
    releaseDate: "1932",
    aboutAuthor:
      "Aldous Huxley was an English writer and philosopher. His dystopian novel 'Brave New World' explores themes of technology, conformity, and the dangers of a totalitarian society.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/41CiEb1Qx2L._SX355_BO1,204,203,200_.jpg",
    title: "The Perks of Being a Wallflower",
    author: "Stephen Chbosky",
    price: 199,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Coming-of-Age"],
    stockQty: 25,
    rating: 4.7,
    pages: 213,
    releaseDate: "February 1, 1999",
    aboutAuthor:
      "Stephen Chbosky is an American novelist, screenwriter, and film director. He is best known for his coming-of-age novel 'The Perks of Being a Wallflower,' which has resonated with readers for its raw and honest portrayal of adolescence, friendship, and self-discovery. Chbosky's work captures the universal experiences of youth and has garnered a dedicated following.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81RdveuYXWL.jpg",
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: ["History"],
    stockQty: 15,
    rating: 4.8,
    pages: 496,
    releaseDate: "1997",
    aboutAuthor:
      "Jared Diamond is an American geographer, historian, and author. He is known for his multidisciplinary approach to understanding human history and societies. In 'Guns, Germs, and Steel,' Diamond explores the factors that have shaped the course of human history, including geography, technology, and culture. His work challenges traditional explanations of inequality among civilizations and offers a compelling perspective on the complexities of human development.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71gwdjwLMPL.jpg",
    title: "Why Has Nobody Told Me This Before?",
    author: "Dr. Julie Smith",
    price: 149,
    originalPrice: 199,
    isBestSeller: false,
    category: ["Self-Help", "Personal Development"],
    stockQty: 10,
    rating: 4.9,
    pages: 256,
    releaseDate: "June 15, 2022",
    aboutAuthor:
      "Dr. Julie Smith has over ten years' experience as a clinical psychologist and was the first professional to use TikTok to give insights on therapy. Her book, 'Why Has Nobody Told Me This Before?' offers practical advice and insights for overcoming common challenges and achieving personal growth. Dr. Julie's work has been praised for its clarity and actionable strategies, making it a must-read for anyone seeking self-improvement.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81Whkax7IGL.jpg",
    title: "Harry Potter and the Deathly Hallows",
    author: "J.K. Rowling",
    price: 249,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Fantasy"],
    stockQty: 15,
    rating: 4.9,
    pages: 607,
    releaseDate: "July 21, 2007",
    aboutAuthor:
      "J.K. Rowling is a British author, best known for creating the Harry Potter series. Her magical world and compelling storytelling have captivated readers of all ages. Rowling's books have sold millions of copies worldwide and have been adapted into a successful film franchise.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81f7bXC-tTL.jpg",
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J.K. Rowling",
    price: 249,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Fantasy"],
    stockQty: 35,
    rating: 4.9,
    pages: 317,
    releaseDate: "July 8, 1999",
    aboutAuthor:
      "J.K. Rowling is a British author, best known for creating the Harry Potter series. Her magical world and compelling storytelling have captivated readers of all ages. Rowling's books have sold millions of copies worldwide and have been adapted into a successful film franchise.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81p2+4nYtkL.jpg",
    title: "Harry Potter and the Half-Blood Prince",
    author: "J.K. Rowling",
    price: 249,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Fantasy"],
    stockQty: 20,
    rating: 4.9,
    pages: 607,
    releaseDate: "July 16, 2005",
    aboutAuthor:
      "J.K. Rowling is a British author, best known for creating the Harry Potter series. Her magical world and compelling storytelling have captivated readers of all ages. Rowling's books have sold millions of copies worldwide and have been adapted into a successful film franchise.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81a4yXpXjnL.jpg",
    title: "Harry Potter and the Order of the Phoenix",
    author: "J.K. Rowling",
    price: 249,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Fantasy"],
    stockQty: 25,
    rating: 4.7,
    pages: 870,
    releaseDate: "June 21, 2003",
    aboutAuthor:
      "J.K. Rowling is a British author, best known for creating the Harry Potter series. Her magical world and compelling storytelling have captivated readers of all ages. Rowling's books have sold millions of copies worldwide and have been adapted into a successful film franchise.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/810jKiNChxL.jpg",
    title: "Harry Potter and the Goblet of Fire",
    author: "J.K. Rowling",
    price: 249,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Fantasy"],
    stockQty: 30,
    rating: 4.8,
    pages: 636,
    releaseDate: "July 8, 2000",
    aboutAuthor:
      "J.K. Rowling is a British author, best known for creating the Harry Potter series. Her magical world and compelling storytelling have captivated readers of all ages. Rowling's books have sold millions of copies worldwide and have been adapted into a successful film franchise.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81S0LnPGGUL.jpg",
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
    price: 249,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Fantasy"],
    stockQty: 40,
    rating: 4.7,
    pages: 251,
    releaseDate: "July 2, 1998",
    aboutAuthor:
      "J.K. Rowling is a British author, best known for creating the Harry Potter series. Her magical world and compelling storytelling have captivated readers of all ages. Rowling's books have sold millions of copies worldwide and have been adapted into a successful film franchise.",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81m1s4wIPML.jpg",
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    price: 249,
    originalPrice: 299,
    isBestSeller: true,
    category: ["Fantasy"],
    stockQty: 50,
    rating: 4.8,
    pages: 223,
    releaseDate: "June 26, 1997",
    aboutAuthor:
      "J.K. Rowling is a British author, best known for creating the Harry Potter series. Her magical world and compelling storytelling have captivated readers of all ages. Rowling's books have sold millions of copies worldwide and have been adapted into a successful film franchise.",
  },
];
